searchPath: /liquibase/project/changelog
changelogFile: db.changelog-master.sql
url: jdbc:sqlserver://sqlserver:1433;databaseName=LogisticaDB;encrypt=true;trustServerCertificate=true
username: sa
password: Logistica#2024
